// src/App.vue
<!--
 * @Author: NMTuan
 * @Email: NMTuan@qq.com
 * @Date: 2023-01-08 17:27:54
 * @LastEditTime: 2023-01-08 18:08:56
 * @LastEditors: NMTuan
 * @Description: 
 * @FilePath: \bitwarden_data_de_duplication\src\App.vue
-->

<template>
  <div class="h-full flex">
    <!-- menu -->
    <div
      class="fixed z-10 h-full overflow-hidden w-0 bg-cool-gray-100/90 border-r-8 border-cool-gray-300/50 transition-all duration-500 hover:(w-64 border-r)"
      :class="menuClass"
    >
      <div class="w-64 h-full">
        <simplebar class="simplebar h-full">
          <LayoutMenuVue />
        </simplebar>
      </div>
    </div>
    <!-- main -->
    <div
      class="flex-1 h-full overflow-hidden ml-0 transition-all duration-500"
      :class="mainClass"
    >
      <simplebar class="simplebar h-full" ref="mainScroll">
        <div
          class="flex items-center justify-between p-4 leading-none bg-cool-gray-50/50 backdrop-blur sticky left-0 top-0 right-0 z-10"
        >
          <div class="flex items-center">
            <LayoutPinVuew v-model:pin="pin" />
            <div class="ml-4 flex items-center">
              <LayoutGuideVue />
            </div>
          </div>
          <LayoutSocialVue />
        </div>
        <div class="w-85% max-w-6xl mx-auto mt-6">
          <RouterView v-slot="{ Component }">
            <component :is="Component" ref="mainView"></component>
          </RouterView>
        </div>
      </simplebar>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from "vue";
import simplebar from "simplebar-vue";

import LayoutMenuVue from "./components/LayoutMenu.vue";
import LayoutGuideVue from "./components/LayoutGuide.vue";
import LayoutPinVuew from "./components/LayoutPin.vue";
import LayoutSocialVue from "./components/LayoutSocial.vue";

const pin = ref(localStorage.getItem("pin") === "1" ? true : false);
const menuClass = computed(() => {
  if (pin.value) {
    return "lg:(w-64 bg-cool-gray-200/50 !border-none)";
  } else {
    return "";
  }
});
const mainClass = computed(() => {
  if (pin.value) {
    return "lg:ml-64";
  } else {
    return "";
  }
});
</script>

<style lang="scss">
html,
body,
#app {
  @apply text-base text-cool-gray-800 bg-cool-gray-50 h-full overflow-hidden;
}
*:focus-visible {
  @apply outline-none;
}

.simplebar {
  &:hover {
    .simplebar-track {
      @apply bg-black/5;
    }
  }

  .simplebar-scrollbar {
    &:before {
      @apply bg-black/50;
    }
  }
}
</style>

// src/App.svelte
<script>
    import { onMount } from 'svelte'
    import Router from 'svelte-spa-router'
    import routes from './routes'
    import SimpleBar from 'simplebar' // or "import SimpleBar from 'simplebar';" if you want to use it manually.
    import LayoutPin from './lib/layout/Pin.svelte'
    import LayoutMenu from './lib/layout/Menu.svelte'

    let pin = localStorage.getItem('pin') === '0' ? false : true
    let menuClass = []
    let mainClass = []

    $: {
        menuClass = [
            'fixed',
            'z-10',
            'h-full',
            'overflow-hidden',
            'w-0',
            'bg-cool-gray-100/90',
            'border-r-8',
            'border-cool-gray-300/50',
            'transition-all',
            'duration-500',
            'hover:(w-64 border-r)'
        ]
        if (pin) {
            menuClass.push('lg:(w-64 bg-cool-gray-200/50 !border-none)')
        }
    }
    $: {
        mainClass = [
            'flex-1',
            'h-full',
            'overflow-hidden',
            'ml-0',
            'transition-all',
            'duration-500'
        ]
        if (pin) {
            mainClass.push('lg:ml-64')
        }
    }

    onMount(() => {
        new SimpleBar(document.getElementById('menuSimplebar'))
        new SimpleBar(document.getElementById('mainSimplebar'))
    })
</script>

<div class="h-full flex">
    <!-- menu -->
    <div class={menuClass.join(' ')}>
        <div class="w-64 h-full ">
            <div id="menuSimplebar" class="h-full">
                <LayoutMenu />
            </div>
        </div>
    </div>
    <!-- main -->
    <div class={mainClass.join(' ')}>
        <div id="mainSimplebar" class="h-full">
            <div
                class="flex items-center justify-between p-4 leading-none backdrop-blur sticky left-0 top-0 right-0 z-10"
            >
                <div class="flex items-center">
                    <LayoutPin bind:state={pin} />
                    <div class="ml-4">Bitwarden 数据处理</div>
                </div>
                <div class="mr-2">
                    <div class="i-ri-github-fill text-2xl" />
                </div>
            </div>
            <div class="w-85% max-w-6xl mx-auto mt-6">
                <Router {routes} />
            </div>
        </div>
    </div>
</div>

<style>
    :global(html),
    :global(body),
    :global(#app) {
        @apply h-full overflow-hidden bg-cool-gray-50;
    }
</style>
